using System;
using System.Collections;
using UnityEngine;
using UnityEngine.AI;

/// <summary>
/// Walker brain: path to the Hesco line, then chew on it until killed.
/// Drives the Animator (Speed / IsAttacking / Die) generated by AssetZombieBuilder.
/// Pooled - the spawner calls OnSpawned() each time this zombie re-enters play.
/// </summary>
[RequireComponent(typeof(NavMeshAgent))]
[RequireComponent(typeof(Health))]
public sealed class ZombieController : MonoBehaviour
{
    private enum State { Seek, Attack, Dead }

    [Header("Attack")]
    [SerializeField] private float attackInterval = 1.6f;
    [SerializeField] private float attackDamagePercent = 2f;

    [Header("Death")]
    [SerializeField] private float corpseLingerSeconds = 4.5f;

    private static readonly int SpeedParam = Animator.StringToHash("Speed");
    private static readonly int IsAttackingParam = Animator.StringToHash("IsAttacking");
    private static readonly int DieParam = Animator.StringToHash("Die");

    private NavMeshAgent agent;
    private Health health;
    private Animator animator;
    private BarrierHealth barrier;
    private Action<ZombieController> releaseToPool;

    private State state;
    private float nextAttackTime;
    private float stuckCheckAfter;

    private void Awake()
    {
        agent = GetComponent<NavMeshAgent>();
        health = GetComponent<Health>();
        animator = GetComponentInChildren<Animator>();
        health.OnDeath += HandleDeath;
    }

    /// <summary>Called once by the spawner when the instance is first created.</summary>
    public void Initialize(BarrierHealth barrierHealth, Action<ZombieController> release)
    {
        barrier = barrierHealth;
        releaseToPool = release;
    }

    /// <summary>Called by the spawner every time this zombie is pulled from the pool.</summary>
    public void OnSpawned(Vector3 position)
    {
        transform.rotation = Quaternion.identity;
        health.ResetHealth();
        state = State.Seek;
        stuckCheckAfter = Time.time + 5f;

        if (animator != null)
        {
            animator.Rebind();   // clean slate after pooling
            animator.Update(0f);
        }

        agent.enabled = true;
        agent.Warp(position);
        agent.isStopped = false;

        // Aim for a random spot along the wall's road-side face. The point sits just
        // inside the carved-out region, so the agent stops at the navmesh edge - i.e.
        // pressed against the Hesco, exactly where a zombie should be.
        float x = UnityEngine.Random.Range(-5.5f, 5.5f);
        agent.SetDestination(new Vector3(x, 0f, 9.6f));
    }

    private void Update()
    {
        if (animator != null)
        {
            float speed = state != State.Dead && agent.enabled ? agent.velocity.magnitude : 0f;
            animator.SetFloat(SpeedParam, speed);
        }

        if (state == State.Seek)
        {
            UpdateSeek();
        }
        else if (state == State.Attack)
        {
            UpdateAttack();
        }
    }

    private void UpdateSeek()
    {
        if (agent.pathPending)
        {
            return;
        }

        bool arrived = agent.remainingDistance <= agent.stoppingDistance + 0.45f;

        // Fallback: if the agent has stalled near the wall (partial path edge cases),
        // treat that as arrival rather than letting it idle forever.
        bool stalledAtWall = Time.time > stuckCheckAfter
            && agent.velocity.sqrMagnitude < 0.0025f
            && transform.position.z < 11.5f;

        if (arrived || stalledAtWall)
        {
            state = State.Attack;
            agent.isStopped = true;
            nextAttackTime = Time.time + attackInterval * 0.5f;

            if (animator != null)
            {
                animator.SetBool(IsAttackingParam, true);
            }
        }
    }

    private void UpdateAttack()
    {
        // Face the wall (the bridge side, -Z).
        transform.rotation = Quaternion.Slerp(
            transform.rotation,
            Quaternion.LookRotation(Vector3.back),
            5f * Time.deltaTime);

        if (Time.time >= nextAttackTime && barrier != null && !barrier.IsDestroyed)
        {
            nextAttackTime = Time.time + attackInterval;
            barrier.TakeDamage(attackDamagePercent);
        }
    }

    private void HandleDeath()
    {
        if (state == State.Dead)
        {
            return;
        }

        state = State.Dead;
        agent.isStopped = true;
        agent.enabled = false;

        if (animator != null)
        {
            animator.SetBool(IsAttackingParam, false);
            animator.SetTrigger(DieParam); // FallingBack: shot from the front, falls away
        }

        StartCoroutine(ReleaseAfterDelay());
    }

    private IEnumerator ReleaseAfterDelay()
    {
        yield return new WaitForSeconds(corpseLingerSeconds);
        releaseToPool?.Invoke(this);
    }
}
